### ISSUE TITLE
Updated `docker-compose` file

### ISSUE THREAD

**Issue by HaresMahmood** [LwynnF/todo-list#2]
To make it work on Windows (shouldn't impact Mac but please check)

```yaml
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postdb
      - POSTGRES_DB=Todos
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  back-end:
    restart: always
    build:
      context: ./src-server
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    environment:
      - DB_TABLE=Todos
      - DB_USER=postgres
      - DB_PASSWORD=postdb
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  front-end:
    build:
      context: ./src-client
      dockerfile: Dockerfile.client
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    ports:
      - "3000:3000"
    command: npm run start
    depends_on:
      - back-end

volumes:
  postgresql:

networks:
  default:
    name: postgresql_default

```
